[package]
name = "portal-solutions-xtp-schema"
version = "0.0.1"
edition = "2024"
license = "MPL-2.0"
description = "Precompiled XTP Schema"

[dependencies]
regress = "0.10.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
